# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-12 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('exec_plan', models.CharField(max_length=10, verbose_name='\u6d4b\u8bd5\u65b9\u6848')),
                ('prj_name', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('case_id', models.CharField(max_length=300, verbose_name='\u7528\u4f8bid')),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=10, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
        ),
    ]
