# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetask',
            name='case_id',
            field=models.CharField(default='', max_length=300, verbose_name='\u7528\u4f8bid'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='prj_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u9879\u76ee\u540d'),
        ),
    ]
