# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0002_auto_20170812_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetask',
            name='author',
            field=models.CharField(default='admin', max_length=10, verbose_name='\u64cd\u4f5c\u4eba'),
        ),
    ]
