# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-21 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0003_auto_20170812_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(max_length=100, verbose_name='\u4efb\u52a1id')),
                ('caseid', models.IntegerField(max_length=100, verbose_name='\u7528\u4f8bid')),
                ('realresult', models.CharField(max_length=300, verbose_name='\u5b9e\u9645\u7ed3\u679c')),
                ('istrue', models.IntegerField(choices=[(0, '\u901a\u8fc7'), (1, '\u4e0d\u901a\u8fc7')], max_length=100, verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6267\u884c\u65f6\u95f4')),
                ('author', models.CharField(default='admin', max_length=10, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
        ),
    ]
