# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0005_casetask_task_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresults',
            name='istrue',
            field=models.IntegerField(choices=[(0, '\u901a\u8fc7'), (1, '\u4e0d\u901a\u8fc7'), (2, '\u672a\u6267\u884c')], default=2, max_length=100, verbose_name='\u662f\u5426\u901a\u8fc7'),
        ),
    ]
