# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0006_auto_20170822_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresults',
            name='caseid',
            field=models.IntegerField(verbose_name='\u7528\u4f8bid'),
        ),
        migrations.AlterField(
            model_name='caseresults',
            name='realresult',
            field=models.CharField(max_length=3000, verbose_name='\u5b9e\u9645\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='caseresults',
            name='taskid',
            field=models.IntegerField(verbose_name='\u4efb\u52a1id'),
        ),
    ]
