# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-23 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0009_auto_20170822_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6d4b\u8bd5\u62a5\u544a\u540d')),
                ('failnum', models.IntegerField(verbose_name='\u603b\u7528\u4f8b\u6570')),
                ('durt', models.IntegerField(verbose_name='\u6d4b\u8bd5\u65f6\u957f')),
                ('creattime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetask.CaseTask', verbose_name='\u6d4b\u8bd5\u4efb\u52a1')),
            ],
        ),
    ]
