# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-23 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0010_resultreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultreport',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='\u603b\u7528\u4f8b\u6570'),
        ),
        migrations.AlterField(
            model_name='resultreport',
            name='failnum',
            field=models.IntegerField(verbose_name='\u5931\u8d25\u6570'),
        ),
    ]
