# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0011_auto_20170823_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresults',
            name='flag',
            field=models.CharField(default='', max_length=100, verbose_name='\u7ed3\u679c\u6279\u6b21'),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='flag',
            field=models.CharField(default='', max_length=100, verbose_name='\u7ed3\u679c\u6279\u6b21'),
        ),
    ]
