# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casetask', '0012_auto_20170824_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresults',
            name='caseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casesPlat.InterCases', verbose_name='\u6d4b\u8bd5\u7528\u4f8b'),
        ),
    ]
