# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfcacePlat', '0003_auto_20170728_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=50, verbose_name='\u7528\u4f8b\u540d\u79f0')),
                ('precondition', models.CharField(max_length=30, verbose_name='\u524d\u63d0\u7528\u4f8b')),
                ('headinfo', models.CharField(max_length=3000, verbose_name='\u5934\u4fe1\u606f')),
                ('param', models.CharField(max_length=3000, verbose_name='\u8bf7\u6c42\u53c2\u6570')),
                ('expectRs', models.CharField(max_length=3000, verbose_name='\u9884\u671f\u7ed3\u679c')),
                ('interid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfcacePlat.Interfaces', verbose_name='\u63a5\u53e3')),
            ],
        ),
    ]
