# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-02 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casesPlat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercases',
            name='author',
            field=models.CharField(default='', max_length=10, verbose_name='\u64cd\u4f5c\u4eba'),
        ),
        migrations.AddField(
            model_name='intercases',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
