# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casesPlat', '0002_auto_20170802_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercases',
            name='expectRs_nums',
            field=models.IntegerField(default=0, verbose_name='\u9884\u671f\u7ed3\u679c\u6570\u91cf'),
        ),
    ]
