# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-05 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interf_url', models.CharField(max_length=50, verbose_name='\u63a5\u53e3url')),
                ('interf_header', models.CharField(max_length=300, verbose_name='\u5934\u4fe1\u606f')),
                ('interf_method', models.CharField(max_length=10, verbose_name='\u65b9\u6cd5')),
                ('interf_param', models.CharField(max_length=300, verbose_name='\u53c2\u6570')),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=10, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=10, verbose_name='\u9879\u76ee\u540d')),
                ('module_name', models.CharField(max_length=10, verbose_name='\u6a21\u5757\u540d')),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=10, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
        ),
        migrations.AddField(
            model_name='interfaces',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfcacePlat.Projects', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
