# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfcacePlat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PROM', to='interfcacePlat.Projects', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='module_name',
            field=models.CharField(max_length=50, verbose_name='\u6a21\u5757\u540d'),
        ),
    ]
