# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfcacePlat', '0002_auto_20170723_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='interf_header',
            field=models.CharField(max_length=3000, verbose_name='\u5934\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='interf_param',
            field=models.CharField(max_length=3000, verbose_name='\u53c2\u6570'),
        ),
    ]
